### ISSUE TITLE
Trigger node output

### ISSUE THREAD

**Issue by goforthanddie** [niklaswall/node-red-contrib-light-scheduler#24] opened 2018-12-20 08:35 UTC
Hi!
First, thanks for your effort in developing this. So I am looking for an option to manually trigger the output of your node. As far as I can see, it triggers automatically when the state changes depending on the schedule, at startup, minutely, or when I inject some payload to override the function. However, I am looking for a way to just trigger the node to output its current state. My application is that I have a bypass for the node if home is not occupied and I want to trigger the schedule to run when the home becomes occupied again. Maybe just an additional injection message that triggers the node to output, without overriding the node :).

Thanks
Samy

**Comment by goforthanddie** [comment] 2019-01-07 21:01
>  Right now I'm injecting a nonsense payload into it to trigger the output, but the warning in the debug window is annoying.

Can you verify that this is working? I actually tried the same and it did not work. I am currently sending two different overrides to force a change and trigger the output, which seems to work but it feels dirty :).

**Comment by davidevertuani** [comment] 2019-01-07 21:11
Yes, it does work. If you have a look at the code it just check the input word and emits a warn if no matching has been found, but still processes the output.
Yesterday I posted a simple pull request to make the node accept "trigger" as input; let's wait for the dev.

**Comment by goforthanddie** [comment] 2019-01-07 22:08
Actually, I checked the code and it appears to me that it should not trigger the output when you send garbage. Yes, it sends the warning that it is not able to interpret the msg.payload and it calls evaluate() anyway. However, evaluate() calls setState() and setState() only triggers the output if either outputfreq is minutely or msg.payload (which is either set to node.onPayload or node.offPayload) has changed compared to the last call. If you send garbage input the evaluate() function decides depending on matchEvent and I fear that this does not guarantee that the output is triggered every time :). If you check in node-red with a debug node behind the scheduler and inject, you should only see the warning but nothing from the debug node unless matchEvent has changed if I understand this correctly.

**Comment by niklaswall** [comment] 2019-04-09 08:38
Merged the pull request #25 that accepts the trigger keyword.

As @goforthanddie says, this will still only trigger the output if anything has changed. Do you want it to also force the output to be sent?

**Comment by goforthanddie** [comment] 2019-04-11 11:26
For me this makes sense to have some trigger that forces the output to be sent, independent from a change. :) Maybe two triggers make sense? Thanks!

**Comment by tsprivate** [comment] 2019-04-30 07:41
I can confirm sending garbage does not generate an output.

It would be great if an output can be initiated with an command like "update" or anything else

**Comment by niklaswall** [comment] 2019-04-30 14:06
Since today's update the trigger keyword will force the output msg to be sent. Please let me know if you find any problem with that!

/Niklas

**Closed by niklaswall** 2019-04-30 14:06 UTC
